# Generated by Django 4.1 on 2023-09-26 15:50

from django.db import migrations, models
import robots.models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="robot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="model",
            field=models.CharField(
                max_length=2, validators=[robots.models.validate_two_characters]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="serial",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="robot",
            name="version",
            field=models.CharField(
                max_length=2, validators=[robots.models.validate_two_characters]
            ),
        ),
    ]
