# Generated by Django 4.1 on 2023-09-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0002_robot_available_alter_robot_id_alter_robot_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
