# Generated by Django 4.1 on 2023-09-27 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0003_robot_quantity"),
        ("orders", "0002_alter_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="robot_serial",
        ),
        migrations.AddField(
            model_name="order",
            name="robot",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="robots.robot",
                to_field="serial",
            ),
            preserve_default=False,
        ),
    ]
