# Generated by Django 4.1 on 2023-09-27 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_robot_serial_order_robot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="robot",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="robot_serial",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
